server:
    port: 8080
spring:
    profiles:
        active: ${SPRING_PROFILES_ACTIVE:local}
    application:
        name: "Autenticacion"
    devtools:
        add-properties: false
    jackson:
        serialization:
            write-dates-as-timestamps: false
        deserialization:
            adjust-dates-to-context-time-zone: false
        time-zone: UTC
        modules:
            - com.fasterxml.jackson.datatype.jsr310.JavaTimeModule

logging:
    level:
        root: INFO
    pattern:
        level: "%5p [${spring.application.name}] [cid:%X{correlationId}]"
    config: ${LOGGING_CONFIG_FILE:classpath:logback-spring.xml}
    file:
        path: ${LOG_PATH:build/logs}

management:
    endpoints:
        web:
            exposure:
                include: "health,prometheus"
    endpoint:
        health:
            probes:
                enabled: true
