spring:
    h2:
        console:
            enabled: true
            path: "/h2"


    liquibase:
        enabled: true
        driver-class-name: com.mysql.cj.jdbc.Driver
        change-log: "classpath:db/db.changelog-master.yaml"
        url: "jdbc:mysql://${adapters.r2dbc.host}:${adapters.r2dbc.port}/${adapters.r2dbc.database}?useUnicode=true&allowPublicKeyRetrieval=true&useSSL=false"
        user: "${adapters.r2dbc.username}"
        password: "${adapters.r2dbc.password}"

springdoc:
    api-docs:
        enabled: true
        path: /v3/api-docs
    swagger-ui:
        enabled: true
    webflux:
        use-root-path: true

jwt:
    secret: mySecretKey123456789012345678901234567890123456789012345678901234567890
    expiration: 24 # hours

adapters:
    r2dbc:
        host: "localhost"
        port: 3306
        database: "autenticacion_db"
        username: "zidjian"
        password: "002092Az"

cors:
    allowed-origins: "http://localhost:8080"